  services:
    web:
      image: nginx
      ports:
        - 89:80
      volumes:
        - /Users/erzenakuriganova/projects/online-shop/docker/nginx.conf:/etc/nginx/conf.d

        - /Users/erzenakuriganova/projects/online-shop:/var/www/html
      restart: always
      depends_on:
        - php-fpm
        - postgres

    php-fpm:
      build: ../online-shop/docker/docker_php
      volumes:
        - /Users/erzenakuriganova/projects/online-shop:/var/www/html
        - ./docker/docker_php/xdebug.ini:/usr/local/etc/php/conf.d/docker-docker_php-xdebug.ini




    postgres:

      image: postgres:13.1
      restart: always
      volumes:
        - ./docker/postgres/data:/var/lib/postgresql/data
      environment:
        - POSTGRES_USER=${POSTGRES_USER}
        - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        - POSTGRES_DB=${POSTGRES_DB}
      ports:
        - 54322:5432



